name: CI/CD Pipiline  

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build with maven
        run: mvn clean install

      - name : Build Docker image
        run: docker build -t my-app-java .

      - name: Run tests
        run: mvn test

  deploy:
    name: deploy to production
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}